export const GET_ASSIGNMENT_QUESTION = 'GET_ASSIGNMENT_QUESTION';
export const ADD_ASSIGNMENT_QUESTION = 'ADD_ASSIGNMENT_QUESTION';
export const SUBMIT_ASSIGNMENT = 'SUBMIT_ASSIGNMENT';
export const GET_ALL_SUBMISSION_BY_QUESTION = 'GET_ALL_SUBMISSION_BY_QUESTION';

